# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm test
          - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  branches:
    master:
      - step:
        cashes:
          - node
        script: # Modify the commands below to build your repository.          
          - docker pull $DOCKER_USER/$CONTAINER_RELEASE_IMAGE:${CI_BUILD_REF_NAME} || true
          - docker build --cache-from $DOCKER_USER/$CONTAINER_RELEASE_IMAGE:${CI_BUILD_REF_NAME} -t $DOCKER_USER/$CONTAINER_RELEASE_IMAGE:commit-${CI_BUILD_ID} .
          - docker tag $DOCKER_USER/$CONTAINER_RELEASE_IMAGE:commit-${BITBUCKET_COMMIT} $DOCKER_USER/$CONTAINER_RELEASE_IMAGE:${CI_BUILD_REF_NAME}
          - docker push $DOCKER_USER/$CONTAINER_RELEASE_IMAGE:${CI_BUILD_REF_NAME}
          - docker push $DOCKER_USER/$CONTAINER_RELEASE_IMAGE:commit-${BITBUCKET_COMMIT}
options:  
  docker: true